import { ProjectTypes } from "@/types";

const projects: ProjectTypes[] = [
  {
    name: "Event Circle",
    mainType: "react",
    previewLink: "https://giftscircle.netlify.app/",
    previewImg: "/projects/product.PNG",
    category: ["React", "Javascript", "Firebase", "Cloudinary", "Chakra UI"],
    description: "A Gift sharing and Event Creation webapp",
    githubUrl: "https://github.com/ayanwumi101/GiftsCircle/tree/dev_cody",
  },
  {
    name: "Bookly Archive",
    mainType: "Next js",
    previewLink: "https://bookly-archive.netlify.app/",
    previewImg: "/projects/bookly.PNG",
    category: ["NextJs", "Chakra UI", 'Javascript', "Cloudinary"],
    description: "Archive for Programming books",
    githubUrl: "https://github.com/ayanwumi101/bookly-jamstack-hack/tree/main",
  },
  {
    name: "iWello",
    previewLink: "https://iwello-fe-dev.onrender.com/",
    mainType: "Next js",
    previewImg: "/projects/iwello.PNG",
    category: ["NextJs", "Typescript", "Chakra UI", "WebRTC", "Firebase"],
    description: "A web app for a healthtech startup",
    githubUrl: "https://github.com/I3I-innovations/iwello_new_app",
  },
  {
    name: "Sneakers",
    previewLink: "https://cody-ecommerce-app.netlify.app/",
    mainType: "react",
    previewImg: "/projects/sneakers.PNG",
    category: [ "React", "Javascript", "CSS", "Redux-toolkit"],
    description: "An ecommerce web app for shoes",
    githubUrl: "https://github.com/ayanwumi101/e-commerce-app",
  },
  {
    name: "Animes List",
    previewLink: "https://cody-animes-list.netlify.app/",
    mainType: "React",
    previewImg: "/projects/animes.PNG",
    category: ["React", "Javascript", "GraphQL", "Apollo Client"],
    description: "An App that shows the list of animes fetched from a GraphQL Api",
    githubUrl: "https://github.com/ayanwumi101/React-and-GraphQl-project",
  },
  {
    name: "Most Starred GitHub Repositories",
    previewLink: "https://cody-github-users-task.netlify.app/",
    mainType: "react",
    previewImg: "/projects/github.PNG",
    category: ["React", "GitHub Api"],
    description: "A list of most starred GitHub repositories",
    githubUrl: "https://github.com/ayanwumi101/paddle-frontend-assesment1",
  },
  {
    name: "EcoScribes",
    previewLink: "https://cody-blog-app.pages.dev/",
    mainType: "react",
    previewImg: "/projects/ecoscribe.PNG",
    category: ["React", "Firebase", "Javascript", "Chakra UI"],
    description: "A full-stack blog application built with React and Firebase",
    githubUrl: "https://github.com/ayanwumi101/fullstack-blog-app",
  },
  {
    name: "GDG Ibadan DevWebsite",
    previewLink: "https://gdg-v2.pages.dev/",
    mainType: "contribution",
    previewImg: "/projects/gdg.PNG",
    category: ["React", "Chakra UI"],
    description: "Website for Google developer Groups (GDG) Ibadan",
    githubUrl: "https://github.com/ayanwumi101/gdg-ibadan-devwebsite",
  },
  {
    name: "Job Listings App",
    previewLink: "",
    mainType: "react",
    previewImg: "/projects/mobile.PNG",
    category: ["React Native", "Javascript", 'Rest Api'],
    description: "A mobile app built with react native that fetches job listings from an api",
    githubUrl: "https://github.com/ayanwumi101/job-listing-mobile-app",
  },
  {
    name: "Vail Wallet",
    previewLink: "https://vailwallet.netlify.app/",
    mainType: "next",
    previewImg: "/projects/vail-wallet.PNG",
    category: ["React", "Javascript"],
    description: "A sinple website for a fintech startup",
    githubUrl: "https://github.com/ayanwumi101/vail-wallet",
  },
  {
    name: "Real Estate App",
    previewLink: "https://github.com/ayanwumi101/real-estate-app",
    mainType: "react",
    previewImg: "/projects/luxury.PNG",
    category: ["React", "Javascript"],
    description: "A real estate web app built with react",
  },
];

export default projects;
